FROM python:3.7

RUN pip install --upgrade pip

# Python files
COPY config.py /src/
COPY ds.py /src/
COPY dsUT.py /src/
COPY DSRequestHandler.py /src/
COPY DiscoveryMessage.py /src/
COPY DiscoveryStates.py /src/
COPY JsonSerializable.py /src/
COPY MeshMessage.py /src/
COPY MeshSerializable.py /src/
COPY MeshServiceManager.py /src/
COPY VisNode.py /src/
# html
COPY ./html/aarcbody.html /html/
COPY ./html/aarcbody2.html /html/
COPY ./html/aarcheader.html /html/
COPY ./html/bad.html /html/
COPY ./html/clock.html /html/
# javascript
COPY ./js/aarcgraph.js /js/
COPY ./js/site.js /js/
COPY ./js/visutils.js /js/

EXPOSE  9998 9999
CMD ["python", "/src/ds.py", "-p 9999"]