FROM python:3.7

# Update
# RUN apk add --update python py-pip

# Install app dependencies
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install requests_html
RUN pip install pandas
RUN pip install Flask
RUN pip install yahoo_fin

# Bundle app source
COPY aarcstockdata.py /src/aarcstockdata.py

EXPOSE  3000
CMD ["python", "/src/aarcstockdata.py", "-p 3000"]